### ISSUE TITLE
Usage questions

### ISSUE THREAD

**Issue by danriedl** [simonlmn/can-wifi-gateway-stiebel-eltron#4]
Hey Simon, great repository!!

Totally want to try that with my heat pump.

https://github.com/simonlmn/can-wifi-gateway-stiebel-eltron/blob/e0e3c47e6d6c3a481ba210b32dd40fb486632b08/README.md?plain=1#L106

Before I go full in with that solution I want to understand of how one can include it in e.g. home assistant.
Could you please provide sample-data of the MQTT topic or your specific setup to include your stiebel eltron device?

How could I use that translate-file from can2mqtt in with your project?
https://github.com/Hunv/can2mqtt/blob/a9b2cb4717d23e6bac56b9b4344bb17feb73fceb/can2mqtt_core/can2mqtt_core/translator/stiebel_eltron/StiebelEltron.json

Thanks in advance!
Dan

**Comment by simonlmn** [comment]
Hi Dan, thank you for you interest in the project!

My setup is based on [OpenHAB](https://www.openhab.org/) and uses the standard HTTP binding to actually poll the gateway every 30 seconds to get new data. It is not very sophisticated but seems to work pretty good. It is running for about 2 years now with the occasional hiccup solved by resetting the gateway (but has been pretty stable for months now without any interruption).

I had added basic MQTT support on request by someone else, but I am not using it myself, so keep that in mind. It does work and I just made a small change where each datapoint/parameter is published to a separate sub-topic. You probably have to read or potentially change the [MQTTClient.h](https://github.com/simonlmn/can-wifi-gateway-stiebel-eltron/blob/main/src/wifi-gateway/MqttClient.h) to see what it does or adapt it to your needs.

Regarding the can2mqtt translate-file: The gateway currently uses are compile-time "definitions" table (see [ValueDefinitions.h](https://github.com/simonlmn/can-wifi-gateway-stiebel-eltron/blob/main/src/wifi-gateway/ValueDefinitions.h)) which it supports and knows how to interpret. I always wanted to switch that for a run-time configuration similar to what you linked, but since what I have now works for me, it did not happen yet. Looking at that file, I think my value definitions should be mostly the same, but maybe some things are missing or different (depends on your heatpump model and what you want to read/write).

So maybe have a look into that if it is sufficient. Of course, you can also try changing the implementation, but I know that this comes with some initial friction (e.g. the current build setup is not that great and I also want to reduce the nesting of projects using sym-links).

**Comment by simonlmn** [comment]
Quick update: as I wrote in the other issue #5, I am working on supporting "runtime-configurable" definition tables to make this project really usable on any heatpump/device which speaks the same basic CAN protocol. May take a moment, but maybe this is also useful for you.
